name: Build C# project

on: 
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration:
          - Release
          
    runs-on: windows-latest

    env:
      Solution_Name: RPConvert.sln
      dot_net: net6.0
      rid_x64: win-x64
      rid_x86: win-x86
      temp_folder: temp
      app_name: RPConv
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0' # replace with your .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
      
  release:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Create the app package
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode /p:AppxBundle=$env:Appx_Bundle
      env:
          Appx_Bundle: Always
          Appx_Bundle_Platforms: x86|x64
          Appx_Package_Build_Mode: StoreUpload
          Configuration: ${{ matrix.configuration }}

    - name: Create archive
      run: Compress-Archive -Path .\bin\Release\* -DestinationPath ${{env.rid_x64 }}.zip
          
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
